version: "3.3"
services:
  master:
    image: crawlabteam/crawlab:latest
    container_name: crawlab_master
    restart: always
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "192.168.5.245" # mongo host address
      CRAWLAB_MONGO_PORT: "27017"
      CRAWLAB_MONGO_DB: "crawlab"
      CRAWLAB_MONGO_USERNAME: "crawlab" # mongo username
      CRAWLAB_MONGO_PASSWORD: "menetrdpsMongo@5" # mongo password
    volumes:
      - "/opt/crawlab/master:/home/data"
    ports:
      - "8080:8080"
    logging:
      driver: json-file
      options:
        max-size: "5g"
        max-file: "50"
