version: '3.8'
services:
  mongo:
    image: mongo:5.0
    restart: on-failure
    ports:
      - 27017:27017
    command: mongod --auth
    volumes:
      - /docker/mongodb/data/db:/data/db # 挂载数据目录
      - /docker/mongodb/data/log:/var/log/mongodb # 挂载日志目录
      - /docker/mongodb/data/config:/etc/mongo # 挂载配置目录

  redis:
    image: redis:5.0
    restart: on-failure
    volumes:
      - /apps/redis/datadir:/data/redis
      - /apps/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /apps/redis/logs:/var/log/redis
    command: redis-server --requirepass SZkj&pcbs@3986
    ports:
      - 6379:6379
